-- =============================================================================
-- Supabase Schema Initialization Migration
-- Timestamp: 20260801000000
-- Description: Complete initial schema for MORN magazine (Tables, Foreign Keys,
--              Indexes, RLS Policies, Triggers, Realtime & Seed Data)
-- =============================================================================

-- ── 1. Расширения PostgreSQL ──────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS pg_net;


-- ── 2. Таблицы ────────────────────────────────────────────────────────────────

-- Партнеры (Affiliate System)
CREATE TABLE IF NOT EXISTS partners (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              TEXT NOT NULL,
    id_telegram       TEXT,
    hostel_name       TEXT,
    owner_name        TEXT,
    whatsapp          TEXT,
    address           TEXT,
    payment_details   TEXT,
    assigned_manager  TEXT,
    created_at        TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Переходы/клики по партнерским ссылкам
CREATE TABLE IF NOT EXISTS partner_clicks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id  BIGINT REFERENCES partners(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Заявки на туры
CREATE TABLE IF NOT EXISTS tour_requests (
    id                 UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    tour_slug          TEXT,
    tour_title         TEXT,
    client_name        TEXT NOT NULL,
    contact_info       TEXT NOT NULL,
    guests_count       INT DEFAULT 1,
    estimated_price    TEXT,
    partner_id         BIGINT REFERENCES partners(id) ON DELETE SET NULL,
    status             TEXT DEFAULT 'Новая' NOT NULL,
    final_price        NUMERIC DEFAULT NULL,
    partner_commission NUMERIC DEFAULT NULL,
    date_of_tour       DATE DEFAULT NULL,
    created_at         TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Заказы трансферов
CREATE TABLE IF NOT EXISTS transfer_orders (
    id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_name     TEXT NOT NULL,
    contact_number    TEXT NOT NULL,
    destination       TEXT NOT NULL,
    pickup_location   TEXT NOT NULL,
    car_class         TEXT,
    passengers_count  INT DEFAULT 1,
    created_at        TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Объявления Co-Sharing (попутчики)
CREATE TABLE IF NOT EXISTS cosharing_listings (
    id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    headline            TEXT NOT NULL,
    description         TEXT,
    departure_datetime  TIMESTAMPTZ NOT NULL,
    pickup_location     TEXT NOT NULL,
    maps_url            TEXT,
    price_scale         JSONB NOT NULL DEFAULT '[]'::jsonb,
    author_message      TEXT NOT NULL,
    author_social_link  TEXT NOT NULL,
    cover_photo_url     TEXT,
    expires_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Чат Co-Sharing объявлений
CREATE TABLE IF NOT EXISTS cosharing_messages (
    id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    listing_id   UUID NOT NULL REFERENCES cosharing_listings(id) ON DELETE CASCADE,
    message      TEXT NOT NULL,
    social_link  TEXT NOT NULL,
    created_at   TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Билеты на мероприятия
CREATE TABLE IF NOT EXISTS event_tickets (
    id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    tour_slug     TEXT NOT NULL,
    client_name   TEXT NOT NULL,
    email         TEXT NOT NULL,
    contact_info  TEXT NOT NULL,
    guests_count  INT DEFAULT 1,
    created_at    TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Таблица связи туров и гидов (для уведомлений в Telegram)
CREATE TABLE IF NOT EXISTS tour_guides (
    tour_slug          TEXT PRIMARY KEY,
    telegram_chat_ids  TEXT[] NOT NULL DEFAULT '{}'
);

-- Динамические шаблоны уведомлений Telegram
CREATE TABLE IF NOT EXISTS notification_templates (
    id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    target_table      TEXT NOT NULL UNIQUE,
    message_template  TEXT NOT NULL
);


-- ── 3. Индексы ────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_cosharing_messages_listing
    ON cosharing_messages(listing_id, created_at);

CREATE INDEX IF NOT EXISTS idx_partner_clicks_partner_id
    ON partner_clicks(partner_id);

CREATE INDEX IF NOT EXISTS idx_tour_requests_partner_id
    ON tour_requests(partner_id);


-- ── 4. RLS (Row Level Security) и Политики ────────────────────────────────────

-- partners
ALTER TABLE partners ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on partners" ON partners;
CREATE POLICY "Allow public read access on partners"
    ON partners FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow public insert on partners" ON partners;
CREATE POLICY "Allow public insert on partners"
    ON partners FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update on partners" ON partners;
CREATE POLICY "Allow public update on partners"
    ON partners FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public delete on partners" ON partners;
CREATE POLICY "Allow public delete on partners"
    ON partners FOR DELETE TO anon, authenticated USING (true);

-- partner_clicks
ALTER TABLE partner_clicks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public insert into partner_clicks" ON partner_clicks;
CREATE POLICY "Allow public insert into partner_clicks"
    ON partner_clicks FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public select on partner_clicks" ON partner_clicks;
CREATE POLICY "Allow public select on partner_clicks"
    ON partner_clicks FOR SELECT TO anon, authenticated USING (true);

-- tour_requests
ALTER TABLE tour_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public insert on tour_requests" ON tour_requests;
CREATE POLICY "Allow public insert on tour_requests"
    ON tour_requests FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read on tour_requests" ON tour_requests;
CREATE POLICY "Allow public read on tour_requests"
    ON tour_requests FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow public update on tour_requests" ON tour_requests;
CREATE POLICY "Allow public update on tour_requests"
    ON tour_requests FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public delete on tour_requests" ON tour_requests;
CREATE POLICY "Allow public delete on tour_requests"
    ON tour_requests FOR DELETE TO anon, authenticated USING (true);

-- transfer_orders
ALTER TABLE transfer_orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can insert transfer_orders" ON transfer_orders;
CREATE POLICY "Anyone can insert transfer_orders"
    ON transfer_orders FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Anyone can read transfer_orders" ON transfer_orders;
CREATE POLICY "Anyone can read transfer_orders"
    ON transfer_orders FOR SELECT TO anon, authenticated USING (true);

-- cosharing_listings
ALTER TABLE cosharing_listings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can read listings" ON cosharing_listings;
CREATE POLICY "Anyone can read listings"
    ON cosharing_listings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can create listings" ON cosharing_listings;
CREATE POLICY "Anyone can create listings"
    ON cosharing_listings FOR INSERT WITH CHECK (true);

-- cosharing_messages
ALTER TABLE cosharing_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can read messages" ON cosharing_messages;
CREATE POLICY "Anyone can read messages"
    ON cosharing_messages FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can send messages" ON cosharing_messages;
CREATE POLICY "Anyone can send messages"
    ON cosharing_messages FOR INSERT WITH CHECK (true);

-- event_tickets
ALTER TABLE event_tickets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can insert event_tickets" ON event_tickets;
CREATE POLICY "Anyone can insert event_tickets"
    ON event_tickets FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Anyone can read event_tickets" ON event_tickets;
CREATE POLICY "Anyone can read event_tickets"
    ON event_tickets FOR SELECT TO anon, authenticated USING (true);

-- tour_guides
ALTER TABLE tour_guides ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access" ON tour_guides;
CREATE POLICY "Allow public read access"
    ON tour_guides FOR SELECT USING (true);

-- notification_templates
ALTER TABLE notification_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access" ON notification_templates;
CREATE POLICY "Allow public read access"
    ON notification_templates FOR SELECT USING (true);


-- ── 5. Storage (Политики загрузки и чтения фото Co-Sharing) ──────────────────

DROP POLICY IF EXISTS "Anyone can upload cosharing photos" ON storage.objects;
DROP POLICY IF EXISTS "Anyone can view cosharing photos" ON storage.objects;

CREATE POLICY "Anyone can upload cosharing photos"
    ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'cosharing-photos');

CREATE POLICY "Anyone can view cosharing photos"
    ON storage.objects FOR SELECT USING (bucket_id = 'cosharing-photos');


-- ── 6. Realtime ───────────────────────────────────────────────────────────────

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'cosharing_messages'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE cosharing_messages;
    END IF;
END $$;


-- ── 7. Функции и Триггеры (Уведомления в Telegram) ──────────────────────────

CREATE OR REPLACE FUNCTION notify_telegram_webhook()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  _payload  jsonb;
  _endpoint text := 'https://your.supabase.co/functions/v1/telegram-webhook';
  _anon_key text := 'sb_publishable_123456';
BEGIN
  _payload := jsonb_build_object(
    'event',      TG_OP,
    'table',      TG_TABLE_NAME,
    'record',     row_to_json(NEW),
    'old_record', CASE WHEN TG_OP = 'UPDATE' THEN row_to_json(OLD) ELSE NULL END
  );

  PERFORM net.http_post(
    url     := _endpoint,
    body    := _payload,
    headers := ('{"Content-Type": "application/json", "Authorization": "Bearer ' || _anon_key || '"}')::jsonb
  );

  RETURN NEW;
END;
$$;

-- Пересоздание триггеров
DROP TRIGGER IF EXISTS trg_telegram_tour_requests        ON tour_requests;
DROP TRIGGER IF EXISTS trg_telegram_tour_requests_update ON tour_requests;
DROP TRIGGER IF EXISTS trg_telegram_transfer_orders      ON transfer_orders;
DROP TRIGGER IF EXISTS trg_telegram_cosharing_listings  ON cosharing_listings;
DROP TRIGGER IF EXISTS trg_telegram_event_tickets        ON event_tickets;

CREATE TRIGGER trg_telegram_tour_requests
    AFTER INSERT ON tour_requests
    FOR EACH ROW EXECUTE FUNCTION notify_telegram_webhook();

CREATE TRIGGER trg_telegram_tour_requests_update
    AFTER UPDATE ON tour_requests
    FOR EACH ROW
    WHEN (NEW.status = 'Оплачено' AND (OLD.status IS DISTINCT FROM NEW.status OR OLD.final_price IS DISTINCT FROM NEW.final_price))
    EXECUTE FUNCTION notify_telegram_webhook();

CREATE TRIGGER trg_telegram_transfer_orders
    AFTER INSERT ON transfer_orders
    FOR EACH ROW EXECUTE FUNCTION notify_telegram_webhook();

CREATE TRIGGER trg_telegram_cosharing_listings
    AFTER INSERT ON cosharing_listings
    FOR EACH ROW EXECUTE FUNCTION notify_telegram_webhook();

CREATE TRIGGER trg_telegram_event_tickets
    AFTER INSERT ON event_tickets
    FOR EACH ROW EXECUTE FUNCTION notify_telegram_webhook();


-- ── 8. Начальные справочные данные (Seed Data) ────────────────────────────────

-- Шаблоны уведомлений
INSERT INTO notification_templates (target_table, message_template)
VALUES
  (
    'cosharing_listings',
    '🚗 <b>Новое объявление Co-Sharing</b>

📌 <b>Заголовок:</b> {{headline}}
📝 <b>Описание:</b> {{description}}
📅 <b>Дата выезда:</b> {{departure_datetime}}
📍 <b>Точка сбора:</b> {{pickup_location}}
🗺 <b>Google Maps:</b> {{maps_url}}

👤 <b>Контакты автора:</b>
{{author_social_link}}'
  ),
  (
    'tour_requests',
    '🏔 <b>Новая заявка на тур</b>

<b>Тур:</b> {{tour_title}}
<b>Имя:</b> {{client_name}}
<b>Контакт:</b> {{contact_info}}
<b>Гостей:</b> {{guests_count}}
<b>Сумма:</b> {{estimated_price}}'
  ),
  (
    'transfer_orders',
    '🚘 <b>Новый заказ трансфера</b>

<b>Имя:</b> {{customer_name}}
<b>Телефон:</b> {{contact_number}}
<b>Направление:</b> {{destination}}
<b>Точка подачи:</b> {{pickup_location}}
<b>Класс авто:</b> {{car_class}}
<b>Пассажиров:</b> {{passengers_count}}'
  ),
  (
    'event_tickets',
    '🎟 <b>Новая покупка билета</b>

<b>Событие:</b> {{tour_slug}}
<b>Имя:</b> {{client_name}}
<b>Email:</b> {{email}}
<b>Контакт:</b> {{contact_info}}
<b>Гостей:</b> {{guests_count}}'
  ),
  (
    'tour_requests_partner',
    '📥 <b>Новая заявка по вашей ссылке!</b>

<b>Тур:</b> {{tour_title}}
<b>Имя:</b> {{client_name}}
<b>Гостей:</b> {{guests_count}}
<b>Сумма:</b> {{estimated_price}}
<i>Статус: В обработке</i>'
  ),
  (
    'tour_requests_paid_partner',
    '💰 <b>FINAL DEAL DETAILS:</b>
• <b>Client:</b> {{client_name}}
• <b>Final Sale Amount:</b> [${{final_price_usd}} / {{final_price_kzt}} ₸]
• <b>Your Earned Commission (5%):</b> [${{partner_commission_usd}} / {{partner_commission_kzt}} ₸]'
  )
ON CONFLICT (target_table) DO UPDATE
  SET message_template = EXCLUDED.message_template;

-- Базовый реестр гидов по турам
INSERT INTO tour_guides (tour_slug, telegram_chat_ids)
VALUES
  ('tour1-essential', ARRAY[]::text[]),
  ('tour2-essential', ARRAY[]::text[]),
  ('tour3-essential', ARRAY[]::text[]),
  ('sovet-peak-4317m', ARRAY[]::text[]),
  ('bao-circuit',      ARRAY[]::text[]),
  ('zaili',            ARRAY[]::text[]),
  ('horseback',        ARRAY[]::text[]),
  ('assy-plateau',     ARRAY[]::text[]),
  ('kolsai-horses',    ARRAY[]::text[]),
  ('bukreyev-peak-3010m', ARRAY[]::text[]),
  ('ormakhai-gorge-1day', ARRAY[]::text[])
ON CONFLICT (tour_slug) DO NOTHING;
